######################################################################
#
# File name : DIVU_tb_wave.do
# Created on: Sun Apr 14 21:30:08 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
