######################################################################
#
# File name : post_sim_tb_compile.do
# Created on: Thu May 23 22:31:51 +0800 2024
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
D:\\win32pe\\vlib work
D:\\win32pe\\vlib msim

D:\\win32pe\\vlib msim/xil_defaultlib

D:\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

D:\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"post_sim_tb_time_synth.v" \
"../../../../CPU31_zyk.srcs/sim_1/new/post_sim_tb.v" \


quit -force

