######################################################################
#
# File name : post_sim_tb_wave.do
# Created on: Thu May 23 22:31:55 +0800 2024
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
