######################################################################
#
# File name : post_sim_tb_simulate.do
# Created on: Thu May 23 22:31:55 +0800 2024
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
vsim -voptargs="+acc" +transport_int_delays +pulse_r/0 +pulse_int_r/0 -L simprims_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.post_sim_tb xil_defaultlib.glbl

do {post_sim_tb_wave.do}

view wave
view structure
view signals

do {post_sim_tb.udo}

run 1000ns
