######################################################################
#
# File name : encoder83_Pri_tb.udo
# Created on: Sun Oct 22 11:22:46 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
