######################################################################
#
# File name : encoder83_Pri_tb_wave.do
# Created on: Sun Oct 22 20:42:34 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
