######################################################################
#
# File name : encoder83_Pri_tb_simulate.do
# Created on: Sun Oct 22 20:42:34 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.encoder83_Pri_tb xil_defaultlib.glbl

do {encoder83_Pri_tb_wave.do}

view wave
view structure
view signals

do {encoder83_Pri_tb.udo}

run 1000ns
