######################################################################
#
# File name : extend_tb_wave.do
# Created on: Fri Sep 22 15:47:26 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
