######################################################################
#
# File name : Adder_tb_compile.do
# Created on: Sat Nov 04 16:44:18 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\win32pe\\vlib work
D:\\win32pe\\vlib msim

D:\\win32pe\\vlib msim/xil_defaultlib

D:\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

D:\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../Adder.v.srcs/sources_1/new/Adder.v" \
"../../../Adder.v.srcs/sources_1/new/Adder_tb.v" \


# compile glbl module
D:\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

