######################################################################
#
# File name : display7_tb_wave.do
# Created on: Sun Jan 14 00:46:09 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
