######################################################################
#
# File name : _246tb_ex10_tb_compile.do
# Created on: Fri Jul 19 09:37:26 +0800 2024
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
D:\\win32pe\\vlib work
D:\\win32pe\\vlib msim

D:\\win32pe\\vlib msim/xil_defaultlib

D:\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

D:\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"_246tb_ex10_tb_time_synth.v" \
"../../../../CPU54.srcs/sim_1/new/testbench_cpu54_single.v" \


quit -force

