######################################################################
#
# File name : _246tb_ex10_tb_wave.do
# Created on: Fri Jul 19 09:37:41 +0800 2024
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
