######################################################################
#
# File name : JK_FF_tb_wave.do
# Created on: Sun Nov 12 11:32:06 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
