######################################################################
#
# File name : logic_gates_tb.udo
# Created on: Wed Sep 20 16:41:07 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
