######################################################################
#
# File name : alu_tb_wave.do
# Created on: Mon Dec 04 22:56:45 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
