######################################################################
#
# File name : three_state_gates_tb_wave.do
# Created on: Fri Sep 22 15:31:24 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
