######################################################################
#
# File name : three_state_gates_tb_compile.do
# Created on: Fri Sep 22 15:31:20 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\win32pe\\vlib work
D:\\win32pe\\vlib msim

D:\\win32pe\\vlib msim/xil_defaultlib

D:\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

D:\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../three_state_gates.srcs/sources_1/new/three_state_gates.v" \
"../../../three_state_gates.srcs/sources_1/new/three_state_gates_tb.v" \


# compile glbl module
D:\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

