######################################################################
#
# File name : three_state_gates_tb.udo
# Created on: Fri Sep 22 15:12:33 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
