######################################################################
#
# File name : MULT_tb_wave.do
# Created on: Sun Apr 07 18:51:15 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
