######################################################################
#
# File name : cpu_tb_wave.do
# Created on: Sat May 18 16:51:00 +0800 2024
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
