######################################################################
#
# File name : cpu_tb_compile.do
# Created on: Sat May 18 16:50:56 +0800 2024
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
D:\\win32pe\\vlib work
D:\\win32pe\\vlib msim

D:\\win32pe\\vlib msim/xil_defaultlib

D:\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

D:\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"cpu_tb_time_synth.v" \


quit -force

