# 
# Synthesis run script generated by Vivado
# 

set_param simulator.modelsimInstallPath D:/win32pe
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/vivado_projects/CPU_Board/CPU_Board.cache/wt [current_project]
set_property parent.project_path D:/vivado_projects/CPU_Board/CPU_Board.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files D:/大学资料/专业课/计组/实验/31条指令CPU实验相关文档/31条CPUcoe文件/mips_31_mars_board_switch.coe
add_files -quiet d:/vivado_projects/CPU_Board/CPU_Board.srcs/sources_1/ip/IPcore_Board/IPcore_Board.dcp
set_property used_in_implementation false [get_files d:/vivado_projects/CPU_Board/CPU_Board.srcs/sources_1/ip/IPcore_Board/IPcore_Board.dcp]
read_verilog -library xil_defaultlib {
  D:/vivado_projects/CPU_Board/CPU_Board.srcs/sources_1/new/MUX.v
  D:/vivado_projects/CPU_Board/CPU_Board.srcs/sources_1/new/RegFile.v
  D:/vivado_projects/CPU_Board/CPU_Board.srcs/sources_1/new/PCreg.v
  D:/vivado_projects/CPU_Board/CPU_Board.srcs/sources_1/new/Controller.v
  D:/vivado_projects/CPU_Board/CPU_Board.srcs/sources_1/new/ALU.v
  D:/vivado_projects/CPU_Board/CPU_Board.srcs/sources_1/new/DMEM.v
  D:/vivado_projects/CPU_Board/CPU_Board.srcs/sources_1/new/CPU.v
  D:/vivado_projects/CPU_Board/CPU_Board.srcs/sources_1/new/sccomp_dataflow.v
  D:/vivado_projects/CPU_Board/CPU_Board.srcs/sources_1/new/Divider.v
  D:/vivado_projects/CPU_Board/CPU_Board.srcs/sources_1/new/seg7x16.v
  D:/vivado_projects/CPU_Board/CPU_Board.srcs/sources_1/new/CPU_Board.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/vivado_projects/CPU_Board/CPU_Board.srcs/constrs_1/new/icf.xdc
set_property used_in_implementation false [get_files D:/vivado_projects/CPU_Board/CPU_Board.srcs/constrs_1/new/icf.xdc]


synth_design -top CPU_Board -part xc7a100tcsg324-1


write_checkpoint -force -noxdef CPU_Board.dcp

catch { report_utilization -file CPU_Board_utilization_synth.rpt -pb CPU_Board_utilization_synth.pb }
