######################################################################
#
# File name : transmission8_tb_wave.do
# Created on: Sun Oct 15 10:18:02 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
