set_property PACKAGE_PIN E3 [get_ports clk_in]
set_property PACKAGE_PIN N17 [get_ports reset]

set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports clk_in]

create_clock -period 100.000 -name clk_pin -waveform {0.000 50.000} [get_ports clk_in]
set_input_delay -clock [get_clocks *] 1.000 [get_ports reset]
set_output_delay -clock [get_clocks *] 0.000 [get_ports -filter { NAME =~  "*" && DIRECTION == "OUT" }]


set_property IOSTANDARD LVCMOS33 [get_ports {inst[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[0]}]


