######################################################################
#
# File name : Asynchronous_D_FF_tb_wave.do
# Created on: Sun Nov 12 11:00:57 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
