######################################################################
#
# File name : logic_gates_tb.udo
# Created on: Mon Sep 18 20:34:23 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
