######################################################################
#
# File name : logic_gates_tb_compile.do
# Created on: Wed Sep 20 16:20:09 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\win32pe\\vlib work
D:\\win32pe\\vlib msim

D:\\win32pe\\vlib msim/xil_defaultlib

D:\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

D:\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../logic_gates_1.srcs/sources_1/new/logic_gates_1.v" \
"../../../logic_gates_1.srcs/sources_1/new/logic_gates_1_tb.v" \


# compile glbl module
D:\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

