# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_param simulator.modelsimInstallPath D:/win32pe
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/vivado_projects/CPU54/CPU54.cache/wt [current_project]
set_property parent.project_path D:/vivado_projects/CPU54/CPU54.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files D:/大学资料/专业课/计组/实验/54条指令CPU实验相关文档/54条CPU_testbench+coe+results比对文件/mips_54_mars_simulate_student_ForWeb_2024.coe
add_files D:/大学资料/专业课/计组/实验/54条指令CPU实验/mips_54_mars_board_switch_student_2024.coe
add_files c:/Users/Miracle/Desktop/mips_54_mars_board_switch_student_2024.coe
add_files -quiet d:/vivado_projects/CPU54/CPU54.srcs/sources_1/ip/dist_mem_gen_1/dist_mem_gen_1.dcp
set_property used_in_implementation false [get_files d:/vivado_projects/CPU54/CPU54.srcs/sources_1/ip/dist_mem_gen_1/dist_mem_gen_1.dcp]
read_verilog -library xil_defaultlib {
  D:/vivado_projects/CPU54/CPU54.srcs/sources_1/new/MUL.v
  D:/vivado_projects/CPU54/CPU54.srcs/sources_1/new/Controller.v
  D:/vivado_projects/CPU54/CPU54.srcs/sources_1/new/Regfile.v
  D:/vivado_projects/CPU54/CPU54.srcs/sources_1/new/PC.v
  D:/vivado_projects/CPU54/CPU54.srcs/sources_1/new/MUX.v
  D:/vivado_projects/CPU54/CPU54.srcs/sources_1/new/HI_LO.v
  D:/vivado_projects/CPU54/CPU54.srcs/sources_1/new/DIV.v
  D:/vivado_projects/CPU54/CPU54.srcs/sources_1/new/Decoder.v
  D:/vivado_projects/CPU54/CPU54.srcs/sources_1/new/CP0.v
  D:/vivado_projects/CPU54/CPU54.srcs/sources_1/new/CLZ.v
  D:/vivado_projects/CPU54/CPU54.srcs/sources_1/new/ALU.v
  D:/vivado_projects/CPU54/CPU54.srcs/sources_1/new/IMEM.v
  D:/vivado_projects/CPU54/CPU54.srcs/sources_1/new/DMEM.v
  D:/vivado_projects/CPU54/CPU54.srcs/sources_1/new/CPU.v
  D:/vivado_projects/CPU54/CPU54.srcs/sources_1/new/sccomp_dataflow.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/vivado_projects/CPU54/CPU54.srcs/constrs_1/new/icf.xdc
set_property used_in_implementation false [get_files D:/vivado_projects/CPU54/CPU54.srcs/constrs_1/new/icf.xdc]


synth_design -top sccomp_dataflow -part xc7a100tcsg324-1


write_checkpoint -force -noxdef sccomp_dataflow.dcp

catch { report_utilization -file sccomp_dataflow_utilization_synth.rpt -pb sccomp_dataflow_utilization_synth.pb }
