######################################################################
#
# File name : barrelshifter32_tb_wave.do
# Created on: Sat Oct 28 13:44:07 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
