######################################################################
#
# File name : pre_sim_tb_compile.do
# Created on: Mon May 20 14:30:42 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\win32pe\\vlib work
D:\\win32pe\\vlib msim

D:\\win32pe\\vlib msim/dist_mem_gen_v8_0_10
D:\\win32pe\\vlib msim/xil_defaultlib

D:\\win32pe\\vmap dist_mem_gen_v8_0_10 msim/dist_mem_gen_v8_0_10
D:\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

D:\\win32pe\\vlog -64 -incr -work dist_mem_gen_v8_0_10  \
"../../../CPU31.ip_user_files/ipstatic/dist_mem_gen_v8_0_10/simulation/dist_mem_gen_v8_0.v" \

D:\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../CPU31.srcs/sources_1/ip/ip1/sim/ip1.v" \
"../../../CPU31.srcs/sources_1/ip/ip2/sim/ip2.v" \
"../../../CPU31.srcs/sources_1/ip/ip3/sim/ip3.v" \
"../../../CPU31.srcs/sources_1/ip/ip4/sim/ip4.v" \
"../../../CPU31.srcs/sources_1/ip/ip5/sim/ip5.v" \
"../../../CPU31.srcs/sources_1/ip/IPcore/sim/IPcore.v" \
"../../../CPU31.srcs/sources_1/ip/ip6/sim/ip6.v" \
"../../../CPU31.srcs/sources_1/ip/ip7/sim/ip7.v" \
"../../../CPU31.srcs/sources_1/new/MUX.v" \
"../../../CPU31.srcs/sources_1/new/RegFile.v" \
"../../../CPU31.srcs/sources_1/new/PCreg.v" \
"../../../CPU31.srcs/sources_1/new/Controller.v" \
"../../../CPU31.srcs/sources_1/new/ALU.v" \
"../../../CPU31.srcs/sources_1/new/DMEM.v" \
"../../../CPU31.srcs/sources_1/new/CPU.v" \
"../../../CPU31.srcs/sources_1/new/sccomp_dataflow.v" \
"../../../CPU31.srcs/sources_1/new/pre_sim_tb.v" \
"../../../CPU31.srcs/sources_1/new/Divider.v" \
"../../../CPU31.srcs/sources_1/new/CPU_Board.v" \
"../../../CPU31.srcs/sources_1/new/seg7x16.v" \
"../../../CPU31.srcs/sources_1/new/cpu_tb.v" \
"../../../CPU31.srcs/sources_1/new/post_sim_tb.v" \

# compile glbl module
D:\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

