######################################################################
#
# File name : pre_sim_tb_simulate.do
# Created on: Mon May 20 14:30:47 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L dist_mem_gen_v8_0_10 -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.pre_sim_tb xil_defaultlib.glbl

do {pre_sim_tb_wave.do}

view wave
view structure
view signals

do {pre_sim_tb.udo}

run 1000ns
