######################################################################
#
# File name : pre_sim_tb_wave.do
# Created on: Mon May 20 14:30:47 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
