######################################################################
#
# File name : FA_tb_wave.do
# Created on: Sat Nov 04 16:37:50 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
