######################################################################
#
# File name : FA_tb_simulate.do
# Created on: Sat Nov 04 16:37:50 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.FA_tb xil_defaultlib.glbl

do {FA_tb_wave.do}

view wave
view structure
view signals

do {FA_tb.udo}

run 1000ns
