######################################################################
#
# File name : Top_compile.do
# Created on: Sun Jan 14 00:22:15 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\win32pe\\vlib work
D:\\win32pe\\vlib msim

D:\\win32pe\\vlib msim/xil_defaultlib

D:\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

D:\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../complex_work.srcs/sources_1/new/Vga_display.v" \
"../../../complex_work.srcs/sources_1/new/LED.v" \
"../../../complex_work.srcs/sources_1/new/keyboard.v" \
"../../../complex_work.srcs/sources_1/new/game.v" \
"../../../complex_work.srcs/sources_1/new/display7.v" \
"../../../complex_work.srcs/sources_1/new/Divider.v" \
"../../../complex_work.srcs/sources_1/new/top.v" \


# compile glbl module
D:\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

