######################################################################
#
# File name : Top_simulate.do
# Created on: Sun Jan 14 00:22:27 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.Top xil_defaultlib.glbl

do {Top_wave.do}

view wave
view structure
view signals

do {Top.udo}

run 1000ns
