######################################################################
#
# File name : MULTU_tb_wave.do
# Created on: Sun Apr 07 18:30:23 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
