######################################################################
#
# File name : decoder_tb_wave.do
# Created on: Mon Oct 16 19:52:32 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
