######################################################################
#
# File name : encoder83_tb.udo
# Created on: Sun Oct 22 10:10:29 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
