######################################################################
#
# File name : Regfiles_tb_wave.do
# Created on: Mon Nov 27 20:06:11 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
