######################################################################
#
# File name : logic_gates_tb.udo
# Created on: Wed Sep 20 17:24:48 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
