######################################################################
#
# File name : logic_gates_tb_wave.do
# Created on: Wed Sep 20 17:24:48 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
