######################################################################
#
# File name : Synchronous_D_FF_tb_wave.do
# Created on: Sun Nov 12 10:36:17 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
