######################################################################
#
# File name : _246tb_ex10_tb_compile.do
# Created on: Fri Jul 12 19:46:55 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\win32pe\\vlib work
D:\\win32pe\\vlib msim

D:\\win32pe\\vlib msim/dist_mem_gen_v8_0_10
D:\\win32pe\\vlib msim/xil_defaultlib

D:\\win32pe\\vmap dist_mem_gen_v8_0_10 msim/dist_mem_gen_v8_0_10
D:\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

D:\\win32pe\\vlog -64 -incr -work dist_mem_gen_v8_0_10  \
"../../../CPU54.ip_user_files/ipstatic/dist_mem_gen_v8_0_10/simulation/dist_mem_gen_v8_0.v" \

D:\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../CPU54.srcs/sources_1/ip/dist_mem_gen_1/sim/dist_mem_gen_1.v" \
"../../../CPU54.srcs/sources_1/new/MUL.v" \
"../../../CPU54.srcs/sources_1/new/Controller.v" \
"../../../CPU54.srcs/sources_1/new/Regfile.v" \
"../../../CPU54.srcs/sources_1/new/PC.v" \
"../../../CPU54.srcs/sources_1/new/MUX.v" \
"../../../CPU54.srcs/sources_1/new/HI_LO.v" \
"../../../CPU54.srcs/sources_1/new/DIV.v" \
"../../../CPU54.srcs/sources_1/new/Decoder.v" \
"../../../CPU54.srcs/sources_1/new/CP0.v" \
"../../../CPU54.srcs/sources_1/new/CLZ.v" \
"../../../CPU54.srcs/sources_1/new/ALU.v" \
"../../../CPU54.srcs/sources_1/new/IMEM.v" \
"../../../CPU54.srcs/sources_1/new/DMEM.v" \
"../../../CPU54.srcs/sources_1/new/CPU.v" \
"../../../CPU54.srcs/sources_1/new/sccomp_dataflow.v" \
"../../../CPU54.srcs/sim_1/new/testbench_cpu54_single.v" \

# compile glbl module
D:\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

