######################################################################
#
# File name : _246tb_ex10_tb_wave.do
# Created on: Fri Jul 12 19:46:59 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
