######################################################################
#
# File name : pcreg_tb_wave.do
# Created on: Sun Nov 12 11:54:38 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
