######################################################################
#
# File name : pcreg_tb.udo
# Created on: Sun Nov 12 09:47:38 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
