######################################################################
#
# File name : selector41_tb_wave.do
# Created on: Sun Oct 15 10:48:55 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
