# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/vivado_projects/CPU_Board/CPU_Board.srcs/sources_1/ip/IPcore_Board/IPcore_Board.xci
# IP: The module: 'IPcore_Board' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado_projects/CPU_Board/CPU_Board.srcs/sources_1/ip/IPcore_Board/IPcore_Board_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'IPcore_Board'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: d:/vivado_projects/CPU_Board/CPU_Board.srcs/sources_1/ip/IPcore_Board/IPcore_Board.xci
# IP: The module: 'IPcore_Board' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado_projects/CPU_Board/CPU_Board.srcs/sources_1/ip/IPcore_Board/IPcore_Board_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'IPcore_Board'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
