######################################################################
#
# File name : de_selector14_tb_wave.do
# Created on: Sun Oct 15 09:04:29 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
