######################################################################
#
# File name : display_tb.udo
# Created on: Mon Oct 16 20:29:23 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
