######################################################################
#
# File name : display7_tb_compile.do
# Created on: Sun Oct 22 20:57:41 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\win32pe\\vlib work
D:\\win32pe\\vlib msim

D:\\win32pe\\vlib msim/xil_defaultlib

D:\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

D:\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../display.srcs/sources_1/new/display.v" \
"../../../display.srcs/sources_1/new/display_tb.v" \


# compile glbl module
D:\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

