######################################################################
#
# File name : display7_tb_wave.do
# Created on: Sun Oct 22 20:57:45 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
