# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/vivado_projects/CPU31/CPU31.srcs/sources_1/ip/ip3/ip3.xci
# IP: The module: 'ip3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado_projects/CPU31/CPU31.srcs/sources_1/ip/ip3/ip3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: d:/vivado_projects/CPU31/CPU31.srcs/sources_1/ip/ip3/ip3.xci
# IP: The module: 'ip3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado_projects/CPU31/CPU31.srcs/sources_1/ip/ip3/ip3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
